Repository TimmyRoom/TimmyRoom, pull requests merged in 2023-05, with the labels that each got.

#72 Update : Vibrate API Document
  Documents/API/API 문서.md
Labels: documentation

#76 Modify : Vibrate Control API for Scene Change System
  Assets/00. Workspace/03. Park/VibrateTest/VibrateTestScene.unity
  Assets/02. Scripts/Global Function/VibrateControl.cs
  Assets/04. Models/Dial(Fixed).fbx.meta
  Documents/API/API 문서.md
  ProjectSettings/TagManager.asset
Labels: documentation, enhancement

#77 Add : Lobby and Scene Move API
  Assets/00. Workspace/03. Park/LobbyTest.meta
  Assets/00. Workspace/03. Park/LobbyTest/Lobby.unity
  Assets/00. Workspace/03. Park/LobbyTest/Lobby.unity.meta
  Assets/00. Workspace/03. Park/LobbyTest/LobbyManager.cs
  Assets/00. Workspace/03. Park/LobbyTest/LobbyManager.cs.meta
  Assets/00. Workspace/03. Park/LobbyTest/LobbyTestUI.cs
  Assets/00. Workspace/03. Park/LobbyTest/LobbyTestUI.cs.meta
  Assets/00. Workspace/03. Park/LobbyTest/SceneMoverTest.prefab
  Assets/00. Workspace/03. Park/LobbyTest/SceneMoverTest.prefab.meta
  Assets/02. Scripts/Global Function/SceneMover.cs
  Documents/API/API 문서.md
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#78 Refactoring SceneRecorder
  Assets/00. Workspace/02. Choi/01. Scenes/Gallery.unity
  Assets/00. Workspace/02. Choi/02. Scripts/GalleryManager.cs
  Assets/00. Workspace/02. Choi/03. Prefabs.meta
  Assets/00. Workspace/02. Choi/03. Prefabs/Cube.prefab
  Assets/00. Workspace/02. Choi/03. Prefabs/Cube.prefab.meta
  Assets/02. Scripts/Global Function/SceneRecorder.cs
Labels: bug, enhancement

#82 Add : GameChart, Note class for convert json
  Assets/02. Scripts/Global Function/GameChart.cs
  Assets/02. Scripts/Global Function/GameChart.cs.meta
  Assets/02. Scripts/Global Function/MusicContentTool.cs
  Assets/02. Scripts/Global Function/Note.cs
  Assets/02. Scripts/Global Function/Note.cs.meta
  Assets/SampleJson.json
Labels: enhancement

#83 Fix : LobbySceneManager
  Assets/00. Workspace/03. Park/LobbyTest/Lobby.unity
  Assets/00. Workspace/03. Park/LobbyTest/LobbySceneManager.cs
  Assets/00. Workspace/03. Park/LobbyTest/LobbySceneManager.cs.meta
  Assets/00. Workspace/03. Park/LobbyTest/LobbyTestUI.cs
Labels: enhancement

#84 Modify : UISelector 기능 변경
  Assets/00. Workspace/03. Park/LobbyTest/Lobby.unity
  Assets/00. Workspace/03. Park/VibrateTest/VibrateTestScene.unity
  Assets/02. Scripts/Prefab/UISelector.cs
  Documents/API/API 문서.md
Labels: documentation, enhancement

#93 Edit: connect lobby and gallery
  Assets/00. Workspace/03. Park/LobbyTest/Lobby.unity
  Assets/00. Workspace/03. Park/LobbyTest/LobbyTestUI.cs
  Assets/03. Prefabs/Environments.meta
  Assets/03. Prefabs/Environments/CircleTable.prefab
  Assets/03. Prefabs/Environments/CircleTable.prefab.meta
  Assets/03. Prefabs/Environments/FlowerVase.prefab
  Assets/03. Prefabs/Environments/FlowerVase.prefab.meta
  Assets/04. Models/Char.fbx.meta
  Assets/04. Models/Char_Tex.png.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#96 Modify : Lobby Asset Structure
  Assets/00. Workspace/03. Park/LobbyTest/SceneMoverTest.prefab
  Assets/00. Workspace/03. Park/LobbyTest/SceneMoverTest.prefab.meta
  Assets/01. Scenes/Lobby.unity
  Assets/01. Scenes/Lobby.unity.meta
  Assets/02. Scripts/Lobby.meta
  Assets/02. Scripts/Lobby/LobbySceneManager.cs
  Assets/02. Scripts/Lobby/LobbySceneManager.cs.meta
  Assets/02. Scripts/Lobby/LobbyTestUI.cs
  Assets/02. Scripts/Lobby/LobbyTestUI.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement
